[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.10.0" }
tokio = { version = "1.20.1", features = ["full"] }
regex = "1.6.0"
http = "0.2.8"
reqwest = { version = "0.11.11", features = ["gzip"] }
