[package]
name = "builder"
version = "0.1.0"
edition = "2018"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib" }
tokio = { version = "1.8.2", features = ["full"] }
regex = "1.4.6"
http = "0.2.4"
reqwest = { version = "0.11.3", features = ["gzip"] }