[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.11.1" }
tokio = { version = "1.26.0", features = ["full"] }
regex = "1.7.3"
http = "0.2.9"
reqwest = { version = "0.11.16", features = ["gzip"] }
