[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.10.1" }
tokio = { version = "1.25.0", features = ["full"] }
regex = "1.7.1"
http = "0.2.9"
reqwest = { version = "0.11.14", features = ["gzip"] }
