[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.9.0" }
tokio = { version = "1.18.0", features = ["full"] }
regex = "1.5.5"
http = "0.2.6"
reqwest = { version = "0.11.10", features = ["gzip"] }
