[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[[example]]
name = "builder"
path = "builder.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.8.2" }
tokio = { version = "1.15.0", features = ["full"] }
regex = "1.5.4"
http = "0.2.6"
reqwest = { version = "0.11.8", features = ["gzip"] }
