[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple"
path = "simple.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.10.1" }
tokio = { version = "1.21.1", features = ["full"] }
