[package]
name = "extract"
version = "0.1.0"
edition = "2021"

[[example]]
name = "extract"
path = "extract.rs"

[dependencies]
lychee-lib = { path = "../../lychee-lib", version = "0.10.0" }
tokio = { version = "1.20.1", features = ["full"] }
